"""Builds the dependency tree of a FastAPI app by reading
``route.dependant`` — the structure FastAPI already builds internally when
each route is registered. Does not reparse signatures by hand or touch the
dependency-resolution engine.
"""

from __future__ import annotations

import asyncio
import functools
import inspect as pyinspect
from collections.abc import Callable, Iterator
from dataclasses import dataclass, field
from typing import NamedTuple

from fastapi import FastAPI
from fastapi.routing import APIRoute

_MAX_REPR_LEN = 60


@dataclass
class DependencyNode:
    """A node in the tree: the endpoint (root) or one of its dependencies."""

    name: str
    call: Callable | None
    is_async: bool
    use_cache: bool
    children: list[DependencyNode] = field(default_factory=list)

    def __iter__(self) -> Iterator[DependencyNode]:
        """Depth-first traversal, including itself."""
        yield self
        for child in self.children:
            yield from child


@dataclass
class RouteDependencyTree:
    path: str
    methods: list[str]
    root: DependencyNode


@dataclass
class DepGraphReport:
    routes: list[RouteDependencyTree]

    def shared_dependencies(self) -> dict[Callable, list[str]]:
        """Callables used as a dependency in 2+ routes, with the paths that
        use them. Compares by function identity, not by name — two
        functions with the same name in different modules don't count as
        the same dependency.
        """
        usage: dict[Callable, set[str]] = {}
        for route in self.routes:
            for node in route.root:
                if node is route.root or node.call is None:
                    continue
                usage.setdefault(node.call, set()).add(route.path)
        return {call: sorted(paths) for call, paths in usage.items() if len(paths) > 1}

    def uncached_dependencies(self) -> list[str]:
        """Names of dependencies with ``use_cache=False`` — recomputed every
        time they appear in a request's resolution tree.
        """
        names: set[str] = set()
        for route in self.routes:
            for node in route.root:
                if node is route.root:
                    continue
                if not node.use_cache:
                    names.add(node.name)
        return sorted(names)


def _node_name(call: Callable | None) -> str:
    if call is None:
        return "<unknown>"
    if isinstance(call, functools.partial):
        # Depends(functools.partial(check_role, role="admin")) is a common
        # pattern for parametrizing a dependency. Without unwrapping, two
        # partials over the same underlying function (role="admin" vs.
        # role="editor") share __name__/__qualname__ and show up as if they
        # were the same dependency.
        inner = _node_name(call.func)
        bound = [_safe_repr(a) for a in call.args]
        bound += [f"{k}={_safe_repr(v)}" for k, v in call.keywords.items()]
        return f"{inner}({', '.join(bound)})" if bound else inner
    # Functions and classes have their own __name__. A class-based
    # dependency (``Depends(SomeClass())``) is an instance with no
    # __name__: naming it via repr() would include the memory address and
    # change on every run, breaking node deduplication in the Mermaid
    # export. In that case, name it after the instance's class.
    target = call if hasattr(call, "__name__") else type(call)
    module = getattr(target, "__module__", "") or ""
    qualname = getattr(target, "__qualname__", None) or target.__name__
    name = f"{module}.{qualname}" if module else qualname
    closure = _closure_repr(target)
    return f"{name}{closure}" if closure else name


def _closure_repr(func: object) -> str:
    """Dependencies generated by a factory function (a common pattern for
    parametrizing limits, roles, etc.) share a __qualname__
    (``make_rate_limiter.<locals>.check``) even though they are distinct
    closures with distinct captured values. Showing the captured variables
    avoids mistaking them for the same dependency.
    """
    code = getattr(func, "__code__", None)
    cells = getattr(func, "__closure__", None)
    if not code or not cells or not code.co_freevars:
        return ""
    parts = []
    for var_name, cell in zip(code.co_freevars, cells):
        try:
            parts.append(f"{var_name}={_safe_repr(cell.cell_contents)}")
        except ValueError:
            continue  # cell not yet assigned
    return "{" + ", ".join(parts) + "}" if parts else ""


def _safe_repr(value: object) -> str:
    text = repr(value)
    if len(text) > _MAX_REPR_LEN:
        text = text[: _MAX_REPR_LEN - 1] + "…"
    return text


def _is_async(call: Callable | None) -> bool:
    if call is None:
        return False
    return bool(asyncio.iscoroutinefunction(call) or pyinspect.isasyncgenfunction(call))


def _build_node(dependant) -> DependencyNode:
    node = DependencyNode(
        name=_node_name(dependant.call),
        call=dependant.call,
        is_async=_is_async(dependant.call),
        use_cache=getattr(dependant, "use_cache", True),
    )
    for sub in getattr(dependant, "dependencies", None) or []:
        node.children.append(_build_node(sub))
    return node


class _ResolvedRoute(NamedTuple):
    dependant: object
    path: str
    methods: list[str]


def _iter_resolved_routes(routes) -> Iterator[_ResolvedRoute]:
    """Walks ``routes`` looking for real HTTP routes, descending into
    routers included via ``include_router()`` — no matter how many levels
    of nesting there are.

    On historical Starlette/FastAPI, ``app.routes`` is a flat list of
    ``APIRoute`` with ``path``/``dependant`` already resolved with the
    accumulated prefix. On newer versions, an included router gets wrapped
    in an object with no public type, and the merging of the prefix and of
    dependencies declared in ``include_router(..., dependencies=[...])`` is
    deferred until each request is resolved — the original ``APIRoute``
    (reachable via ``original_router.routes``) is left with the path
    *without* the prefix and the dependant *without* those extra
    dependencies.

    That object still exposes the already-merged result through a method
    (``effective_candidates()``); it's used when available, with a silent
    fallback to the original router if it doesn't exist or changes shape —
    the prefix/inclusion dependencies are lost in that case, but
    introspection never breaks entirely.
    """
    for route in routes:
        if isinstance(route, APIRoute):
            yield _ResolvedRoute(
                route.dependant, route.path, sorted(route.methods or [])
            )
            continue

        effective_candidates = getattr(route, "effective_candidates", None)
        if callable(effective_candidates):
            try:
                candidates = list(effective_candidates())
            except Exception:  # noqa: BLE001 — internal API with no contract, fallback is intentional
                candidates = None
            if candidates is not None:
                yield from _iter_resolved_routes(candidates)
                continue

        dependant = getattr(route, "dependant", None)
        path = getattr(route, "path", None)
        methods = getattr(route, "methods", None)
        if dependant is not None and path is not None and methods is not None:
            # _EffectiveRouteContext-like: already resolved (path with
            # prefix, dependant merged). ``methods`` (unlike an
            # APIWebSocketRoute, which also has ``dependant``/``path`` but
            # isn't an HTTP route) confirms this is a real HTTP route.
            yield _ResolvedRoute(dependant, path, sorted(methods))
            continue

        nested = getattr(route, "routes", None)
        if nested is None:
            original_router = getattr(route, "original_router", None)
            nested = getattr(original_router, "routes", None)
        if nested:
            yield from _iter_resolved_routes(nested)


def inspect_app(app: FastAPI) -> DepGraphReport:
    """Main entry point: walks ``app``'s routes and builds a dependency
    tree for each one, from ``route.dependant``.
    """
    routes: list[RouteDependencyTree] = []
    for resolved in _iter_resolved_routes(app.routes):
        root = _build_node(resolved.dependant)
        routes.append(
            RouteDependencyTree(path=resolved.path, methods=resolved.methods, root=root)
        )
    return DepGraphReport(routes=routes)
